### ISSUE TITLE
Where is the getUserItems defined?

### ISSUE THREAD

**Issue by y0unghe** [mongodb-university/realm-template-apps#129]
I am trying to figure out how the flexible sync works, and when I am looking at this code:

```
Realm initRealm(User currentUser) {
  Configuration config = Configuration.flexibleSync(currentUser, [Item.schema]);
  Realm realm = Realm(
    config,
  );
  final userItemSub = realm.subscriptions.findByName('getUserItems');
  if (userItemSub == null) {
    realm.subscriptions.update((mutableSubscriptions) {
      // server-side rules ensure user only downloads own items
      mutableSubscriptions.add(realm.all<Item>(), name: 'getUserItems');
    });
  }
  return realm;
}
```
I am wondering, where is the `getUserItems` is defined? I can't find in the codebase:  the https://github.com/mongodb/template-app-dart-flutter-todo.git

**Comment by cbush** [comment]
Hi, thanks for your question! getUserItems is an arbitrary name of the subscription -- you can see the subscription is named that in the `mutableSubscriptions.add(...)` line. For more info on subscriptions, see https://www.mongodb.com/docs/realm/sdk/flutter/sync/manage-sync-subscriptions/ . Hope this helps!
