### ISSUE TITLE
Call To Function is not passing the arguments 

### ISSUE THREAD

**Issue by josmanperez** [mongodb-university/realm-template-apps#146]
Hello team. Not sure if this is the right channel. But I was working on a presentation and using the template tiered from our [docs](https://www.mongodb.com/docs/atlas/app-services/sync/app-builder/device-sync-permissions-guide/#tiered-privileges), I realise there was something wrong. 

So, inspecting further, I've seen that the call to function joinTeam is doing

```js
const adminFuncArgs = [admin.id, "greenTeam", true /* make admin */];
const adminFuncResult = await admin.callFunction("joinTeam", adminFuncArgs);
```

The arguments are passed in an `Array`. The App Services function is defined as `exports = async function (userId, teamName, isAdmin = false)` and the problem is that all the arguments are stored in `userId` instead of being spread. 

Therefore `userId = [admin.id, "greenTeam", true]` and `teamName = undefined`. So the `$set` is not working as expected as the filter will never work

The fix is pretty simple, just by editing two lines as follows: 

```js
const adminFuncResult = await admin.callFunction("joinTeam", admin.id, "greenTeam", true);
const funcResult = await member.callFunction("joinTeam", member.id, "greenTeam", false);
```

**Comment by cbush** [comment]
Thanks for raising. Should be handled by https://github.com/mongodb-university/realm-template-apps/pull/147
