### ISSUE TITLE
Realm Prop load error

### ISSUE THREAD

**Issue by hapidashary** [mongodb-university/realm-template-apps#173]
When running the code through the android simulator, it errors out when initializing the RealmProvider. I get the following errors:

 BUNDLE  ./index.js

 LOG  View your data in MongoDB Atlas: https://cloud.mongodb.com/links/<...>/explorer/Cluster0/database/collection/find.
 ERROR  Error: Exception in HostObject::get for prop 'Realm': java.lang.UnsatisfiedLinkError: couldn't find DSO to load: librealm.so caused by: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/~~UrHcuOA1X7s9x-M8jCfU4g==/com.synctutorial-q5oSJsHgqnnBeIlJ_Vt4TQ==/lib/x86_64/librealm.so"... result: 0, js engine: hermes
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 10): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient.        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 10): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient.        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes

**Comment by krollins-mdb** [comment]
Hi, @hapidashary! Thanks for submitting this issue. Could you share some more information?
- How are you getting the app code? By cloning/forking this repo , downloaded from the App Services UI, or through the App Services CLI?
- What Node.js version are you running?

**Comment by hapidashary** [comment]
I have tried it through the App Services UI and the App Services CLI with the same result. I'm running Node 20.9.0 with JDK 11, following the react setup referenced in the readme.

**Comment by krollins-mdb** [comment]
@hapidashary, I have a draft PR up that should fix this: #177 

Hopefully, we can get this merged next week. After that, the updated project code should be available from the CLI and UI when App Services itself does a release.

**Comment by krollins-mdb** [comment]
The template app update has been merged. Updated code won't be deployed to the App Services UI or CLI until they do another release (usually a weekly thing). You could pull directly from this repo if you don't want to wait.

**Comment by krollins-mdb** [comment]
😄 Please let me know if you run into any problems. We can reopen this issue if needed - or create a new one.
