### ISSUE TITLE
EMpty template app

### ISSUE THREAD

**Issue by georgekarlr** [mongodb-university/realm-template-apps#176]
When I download the template app it's empty - and I want to download because of the link
![Screenshot 2023-11-19 052921](https://github.com/mongodb-university/realm-template-apps/assets/130721675/debd095a-888f-4f49-92f1-a4a283de7f3d)
![Screenshot 2023-11-19 052914](https://github.com/mongodb-university/realm-template-apps/assets/130721675/a78e8107-6c7c-4b2d-8bf1-a42f9f25c9f2)
![Screenshot 2023-11-19 052900](https://github.com/mongodb-university/realm-template-apps/assets/130721675/2287c216-baf1-4bd6-bde0-dc29e515b4c7)
![Screenshot 2023-11-19 052848](https://github.com/mongodb-university/realm-template-apps/assets/130721675/48cb71d2-eb54-4a87-908b-c2df769feeb6)

**Comment by dacharyc** [comment]
Hey there @georgekarlr - sorry you had trouble with that! We've been doing some updates to our infrastructure around this, so it's possible we had a disruption. I just attempted this and wasn't able to replicate this problem. I'm wondering if it was a transient issue, or if it may be platform specific.

Just to unblock you, I want to mention we do have a clonable GitHub repository with the client code. It looks like you're trying to use the Kotlin client - you can find that here: https://github.com/mongodb/template-app-kotlin-todo

It's not quite as convenient as the zip download - you'll need to manually populate the values listed in the README - but it can give you a starting point to experiment with the client code.

To try to diagnose the problem with the zip file download, can you give us some more details? From your screenshots, it looks like you're:

- On a Windows machine
- Using Google Chrome as the browser
- Downloading the Kotlin (Android) client code

Is that all correct?

And when you open the zip file that you have successfully downloaded, it contains no files?

**Comment by georgekarlr** [comment]
Yes
